// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Invite defines model for Invite.
type Invite struct {
	Accepted        bool      `json:"accepted"`
	Additional      *[]string `json:"additional,omitempty"`
	AdditionalCount int       `json:"additionalCount"`
	People          []string  `json:"people"`
}

// InviteUpdate defines model for InviteUpdate.
type InviteUpdate struct {
	Accepted   bool      `json:"accepted"`
	Additional *[]string `json:"additional,omitempty"`
}

// PutInviteJSONRequestBody defines body for PutInvite for application/json ContentType.
type PutInviteJSONRequestBody = InviteUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Get an invite by ID
	// (GET /invites/{id})
	GetInvite(c *gin.Context, id openapi_types.UUID)
	// Accept an invite
	// (PUT /invites/{id})
	PutInvite(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInvite(c, id)
}

// PutInvite operation middleware
func (siw *ServerInterfaceWrapper) PutInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInvite(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/invites/:id", wrapper.GetInvite)
	router.PUT(options.BaseURL+"/invites/:id", wrapper.PutInvite)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RUTW/UMBD9K9HQG2GT0nLJrRRUVuJQgRCHbpGm8WzWJbFde1xYrfLf0Tjpx360XEqB",
	"U6x4PO/Nm3mzgtp2zhoyHKBaQagX1GE6vvfeejk4bx151pR+dxQCNiRHXjqCCgJ7bRro+xw8XUXtSUF1",
	"dht4nt8E2otLqhn6HD4Qtrz4RMFZE2gbJDByDL/HGON2QUzNteYdqbGuybE8v01+YW1LaOQVKqVZW4Ot",
	"3Gumbiham49kGl5AtZ+DQ2byBir4djabudXx0uu21XWfzWavzl/uQb5JO4cOf06HbG9ub9F7XK6jHtto",
	"+B41bZga8hLkyLqW1mhtoawn3hBrTLANl9+J8rCSX5zC/0PPjbIfqU1CtZlboaQo1F47IQsVHJ1Os7n1",
	"WYcGG22a7AcpJV8tYqBEBaGlWVoCX8fbQars6HQKOVyTD0O2/Uk5KYW1dWTQaajgYFJODiDVvkiSFIvk",
	"CTk2lEZAVE5IUwUVnBAPrgEpbzBOevi6LOVTW8M0zA461+o6PS0ugzC4Mbac9jzNoYIXxZ3zi9H2xYYv",
	"k0Drwnwmf61rynTIBsKD4CF2HfolVKO1s3pB9fd0VSTJKBQrrfrHyhsdK5p47IjJB6jOVqAFV3SCHAx2",
	"yRYK7jeZfaT8Xolz6ztkqCDGFLm5RM7/oIRjFTukG4djbqNRMgyH5eGToQ7L+mFQY/kGeK1bJ8QZmmGq",
	"KbtYZtN3adfEHS06jc/doqtIgd9atXzi7oy7rF9fFUKx/5uTEROtcTbKZ5kNbLXKRqH/lZk8Sgv7biwl",
	"Rf8rAAD//+VEISOpCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
