// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Invite defines model for Invite.
type Invite struct {
	Additional      *[]string `json:"additional,omitempty"`
	AdditionalCount int       `json:"additionalCount"`
	IsAccepted      bool      `json:"isAccepted"`
	IsOpened        bool      `json:"isOpened"`
	People          []string  `json:"people"`
}

// InviteUpdate defines model for InviteUpdate.
type InviteUpdate struct {
	Additional *[]string `json:"additional,omitempty"`
	IsAccepted bool      `json:"isAccepted"`
}

// PutInviteJSONRequestBody defines body for PutInvite for application/json ContentType.
type PutInviteJSONRequestBody = InviteUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /health)
	GetHealth(c *gin.Context)
	// Get an invite by ID
	// (GET /invites/{id})
	GetInvite(c *gin.Context, id openapi_types.UUID)
	// Accept an invite
	// (PUT /invites/{id})
	PutInvite(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInvite(c, id)
}

// PutInvite operation middleware
func (siw *ServerInterfaceWrapper) PutInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutInvite(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.GET(options.BaseURL+"/invites/:id", wrapper.GetInvite)
	router.PUT(options.BaseURL+"/invites/:id", wrapper.PutInvite)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xUT2/bPgz9KgZ/vf282F27i29dN3QBBqzYMOzQdIBqMY46W1IlqlsQ+LsPlNw2zp/u",
	"0nU9mQkp8vHxkSuoTWeNRk0eqhX4eoGdiOZ754xjwzpj0ZHC+HeH3osG2aSlRajAk1O6gb7PweFNUA4l",
	"VBf3gZf5XaC5usaaoM/hA4qWFp/RW6M9bhfxJCj4P9cY4naVmOpbRTtSCykVKaNFy78UYZfaUvoj6oYW",
	"UB3mYAUROg0VfL+YzezqdOlU26q6z2azV5f/H0C+CSyHTvyapmxv7r3CObFk50PVUxM0rXWmNGGDjoOU",
	"P6lrtMS93fuvjGlR6OT/ZFHv81o0tsVRU1sYx7A2yBwSbIMdIVuDsZ/2r1aKl0P+47xusLAWvN0fBys9",
	"N5xHoq+dstwOVHByPs3mxmWd0KJRusl+opT8VUyI4CjPwBXxjODb4E10ZSfnU8jhFp1P2Q4n5aRk6Mai",
	"FlZBBUeTcnIEkZ1FJK1YxCVis8GoKGY6VppKqOAMKa0ZcINp0+LD12XJn9powiRFYW2r6vi0uPaM4O4S",
	"sHXgcA4V/Fc8nIpiuBPFxiJHgsbEfEF3q2rMlM8S4CQ8H7pOuCVUwy3I6gXWP6KriJShL1ZK9o+1N6w4",
	"c+JEh4TOQ3WxAsV1mSfIQYsubpmE9TGTC5ivtTg3rhMEFYQQIzevzuVfpHDoYgd1gzjmJmjJYjguj5+s",
	"arru+4tqQ3eFR9M6Q8qETqrG7GqZTd/F4xN2jOg8PPeIbgJ6emvk8omnM9yzfnwsGGL/L5URIqxBG+Wz",
	"aEO0SmYD0S9Fk+lgP8iSU/S/AwAA//+7LRHC2ggAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
